"""Intergrate Hero with DateimeMixin

Revision ID: 42022bfd0269
Revises: 902aac14d239
Create Date: 2025-08-13 14:12:38.906404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42022bfd0269'
down_revision: Union[str, Sequence[str], None] = '902aac14d239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('heroes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_heroes_created_at'), 'heroes', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroes_created_at'), table_name='heroes')
    op.drop_column('heroes', 'updated_at')
    op.drop_column('heroes', 'created_at')
    # ### end Alembic commands ###
