"""add powers column to heroes table

Revision ID: 902aac14d239
Revises: 6185a991de0c
Create Date: 2025-08-12 10:57:30.550975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902aac14d239'
down_revision: Union[str, Sequence[str], None] = '6185a991de0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('powers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'powers')
    # ### end Alembic commands ###
